-- =============================================================
-- KigenTask - Demo Seed Data (idempotent)
-- Includes: roles, users, user_role, projects, tasks, comments
-- =============================================================

BEGIN;

-- Ensure base roles exist.
INSERT INTO app_role (name)
VALUES ('ROLE_USER'), ('ROLE_ADMIN')
ON CONFLICT (name) DO NOTHING;

-- Demo users (password for all demo accounts: Password123!).
-- BCrypt hash generated by Spring Security BCryptPasswordEncoder.
INSERT INTO app_user (username, email, password_hash, full_name, is_active)
SELECT 'demo_owner', 'demo.owner@example.com', '$2a$10$YQluSlAjT/3hZ2b6nXIdVOxcG8Is9E4kmUMeYX9urrmB03NGnktNq', 'Demo Owner', TRUE
WHERE NOT EXISTS (
    SELECT 1 FROM app_user WHERE username = 'demo_owner' OR email = 'demo.owner@example.com'
);

INSERT INTO app_user (username, email, password_hash, full_name, is_active)
SELECT 'demo_assignee', 'demo.assignee@example.com', '$2a$10$YQluSlAjT/3hZ2b6nXIdVOxcG8Is9E4kmUMeYX9urrmB03NGnktNq', 'Demo Assignee', TRUE
WHERE NOT EXISTS (
    SELECT 1 FROM app_user WHERE username = 'demo_assignee' OR email = 'demo.assignee@example.com'
);

INSERT INTO app_user (username, email, password_hash, full_name, is_active)
SELECT 'demo_reviewer', 'demo.reviewer@example.com', '$2a$10$YQluSlAjT/3hZ2b6nXIdVOxcG8Is9E4kmUMeYX9urrmB03NGnktNq', 'Demo Reviewer', TRUE
WHERE NOT EXISTS (
    SELECT 1 FROM app_user WHERE username = 'demo_reviewer' OR email = 'demo.reviewer@example.com'
);

INSERT INTO app_user (username, email, password_hash, full_name, is_active)
SELECT 'demo_admin', 'demo.admin@example.com', '$2a$10$YQluSlAjT/3hZ2b6nXIdVOxcG8Is9E4kmUMeYX9urrmB03NGnktNq', 'Demo Admin', TRUE
WHERE NOT EXISTS (
    SELECT 1 FROM app_user WHERE username = 'demo_admin' OR email = 'demo.admin@example.com'
);

-- Assign roles.
INSERT INTO user_role (user_id, role_id)
SELECT u.id, r.id
FROM app_user u
JOIN app_role r ON r.name = 'ROLE_USER'
WHERE u.username IN ('demo_owner', 'demo_assignee', 'demo_reviewer', 'demo_admin')
ON CONFLICT (user_id, role_id) DO NOTHING;

INSERT INTO user_role (user_id, role_id)
SELECT u.id, r.id
FROM app_user u
JOIN app_role r ON r.name = 'ROLE_ADMIN'
WHERE u.username = 'demo_admin'
ON CONFLICT (user_id, role_id) DO NOTHING;

-- Demo projects.
INSERT INTO project (owner_user_id, name, project_key, description)
SELECT u.id, 'Platform Operations', 'DEMOOPS', 'Demo project for infrastructure and deployment tracking.'
FROM app_user u
WHERE u.username = 'demo_owner'
  AND NOT EXISTS (SELECT 1 FROM project p WHERE p.project_key = 'DEMOOPS');

INSERT INTO project (owner_user_id, name, project_key, description)
SELECT u.id, 'Customer Portal', 'DEMOWEB', 'Demo project for frontend and OAuth user journey.'
FROM app_user u
WHERE u.username = 'demo_owner'
  AND NOT EXISTS (SELECT 1 FROM project p WHERE p.project_key = 'DEMOWEB');

-- Demo tasks for project DEMOOPS.
INSERT INTO task (project_id, reporter_user_id, assignee_user_id, title, description, status, priority, due_date)
SELECT p.id, reporter.id, assignee.id,
       'Bootstrap API security',
       'Harden JWT flow and endpoint protections.',
       'IN_PROGRESS'::task_status,
       'HIGH'::task_priority,
       CURRENT_DATE + 7
FROM project p
JOIN app_user reporter ON reporter.username = 'demo_owner'
JOIN app_user assignee ON assignee.username = 'demo_assignee'
WHERE p.project_key = 'DEMOOPS'
  AND NOT EXISTS (
      SELECT 1 FROM task t WHERE t.project_id = p.id AND t.title = 'Bootstrap API security'
  );

INSERT INTO task (project_id, reporter_user_id, assignee_user_id, title, description, status, priority, due_date)
SELECT p.id, reporter.id, assignee.id,
       'Review Docker baseline',
       'Validate compose startup and image size optimizations.',
       'TODO'::task_status,
       'MEDIUM'::task_priority,
       CURRENT_DATE + 10
FROM project p
JOIN app_user reporter ON reporter.username = 'demo_owner'
JOIN app_user assignee ON assignee.username = 'demo_reviewer'
WHERE p.project_key = 'DEMOOPS'
  AND NOT EXISTS (
      SELECT 1 FROM task t WHERE t.project_id = p.id AND t.title = 'Review Docker baseline'
  );

-- Demo tasks for project DEMOWEB.
INSERT INTO task (project_id, reporter_user_id, assignee_user_id, title, description, status, priority, due_date)
SELECT p.id, reporter.id, assignee.id,
       'Integrate Google login button',
       'Implement Google Identity Services and backend token validation.',
       'DONE'::task_status,
       'HIGH'::task_priority,
       CURRENT_DATE - 1
FROM project p
JOIN app_user reporter ON reporter.username = 'demo_owner'
JOIN app_user assignee ON assignee.username = 'demo_assignee'
WHERE p.project_key = 'DEMOWEB'
  AND NOT EXISTS (
      SELECT 1 FROM task t WHERE t.project_id = p.id AND t.title = 'Integrate Google login button'
  );

INSERT INTO task (project_id, reporter_user_id, assignee_user_id, title, description, status, priority, due_date)
SELECT p.id, reporter.id, assignee.id,
       'Prepare production checklist',
       'Document CORS, TLS, and environment setup for deployment.',
       'IN_REVIEW'::task_status,
       'CRITICAL'::task_priority,
       CURRENT_DATE + 3
FROM project p
JOIN app_user reporter ON reporter.username = 'demo_owner'
JOIN app_user assignee ON assignee.username = 'demo_reviewer'
WHERE p.project_key = 'DEMOWEB'
  AND NOT EXISTS (
      SELECT 1 FROM task t WHERE t.project_id = p.id AND t.title = 'Prepare production checklist'
  );

-- Demo comments.
INSERT INTO task_comment (task_id, author_user_id, content)
SELECT t.id, u.id, 'JWT filter and role checks are already in place.'
FROM task t
JOIN app_user u ON u.username = 'demo_owner'
WHERE t.title = 'Bootstrap API security'
  AND NOT EXISTS (
      SELECT 1 FROM task_comment c WHERE c.task_id = t.id AND c.content = 'JWT filter and role checks are already in place.'
  );

INSERT INTO task_comment (task_id, author_user_id, content)
SELECT t.id, u.id, 'Google sign-in flow validated in local docker stack.'
FROM task t
JOIN app_user u ON u.username = 'demo_assignee'
WHERE t.title = 'Integrate Google login button'
  AND NOT EXISTS (
      SELECT 1 FROM task_comment c WHERE c.task_id = t.id AND c.content = 'Google sign-in flow validated in local docker stack.'
  );

INSERT INTO task_comment (task_id, author_user_id, content)
SELECT t.id, u.id, 'Please confirm production allowed origins before release.'
FROM task t
JOIN app_user u ON u.username = 'demo_reviewer'
WHERE t.title = 'Prepare production checklist'
  AND NOT EXISTS (
      SELECT 1 FROM task_comment c WHERE c.task_id = t.id AND c.content = 'Please confirm production allowed origins before release.'
  );

COMMIT;
